# Generated by Django 5.1.3 on 2024-12-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
